package ClienteATM;

import RMI_ATM.ATM;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class Retiro extends javax.swing.JFrame {
    
    String doc_id;
    String[] cuentas;
    String cuenta;
    float saldo = 0;
    String monto;

    public Retiro(String doc) {
        this.doc_id = doc;
        initComponents();
        cuentas();
    }

    public void cuentas(){
        try{
            Registry r = LocateRegistry.getRegistry("127.0.0.1", 1234);
            ATM bank = (ATM) r.lookup("ATM");
            this.cuentas = bank.consultarcuentas(this.doc_id);
            int i = 0;
            while (i !=  6){
                if (this.cuentas[i]!=null){
                    String c = "N° de cuenta "+this.cuentas[i]+" con saldo de "+this.cuentas[i+1];
                    cbcuenta.addItem(c);
                }
                i = i + 2;
            }
        }catch(Exception e){
            System.out.print(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbcuenta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Retirar = new javax.swing.JButton();
        txtmonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Retiro");

        volver.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Cuenta a retirar");

        cbcuenta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Monto a retirar");

        Retirar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Retirar.setText("Retirar");
        Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarActionPerformed(evt);
            }
        });

        txtmonto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Retirar))
                            .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(cbcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Retirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(volver)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        MenuT mt = new MenuT(this.doc_id);
        mt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarActionPerformed
        try{
            this.monto = txtmonto.getText();
            Pattern p = Pattern.compile("[A-Z,a-z,&%$#@!()*^]"); 
            Matcher m = p.matcher(this.monto);
            if (m.find() || Float.parseFloat(this.monto)<0){
                JOptionPane.showMessageDialog(null, "Por favor ingrese solo numeros positivos");
                txtmonto.setText("");
                return;
            }
            if (cbcuenta.getSelectedIndex()==0){
                this.cuenta = this.cuentas[0];
                this.saldo = Float.parseFloat(this.cuentas[1]) - Float.parseFloat(this.monto);
            }if (cbcuenta.getSelectedIndex()==1){
                this.cuenta = this.cuentas[2];
                this.saldo = Float.parseFloat(this.cuentas[3]) - Float.parseFloat(this.monto);
            }if(cbcuenta.getSelectedIndex()==2){
                this.cuenta = this.cuentas[4];
                this.saldo = Float.parseFloat(this.cuentas[5]) - Float.parseFloat(this.monto);
            }
            if (this.saldo<0){
                JOptionPane.showMessageDialog(null, "El monto colocado es superior al saldo de la cuenta");
                txtmonto.setText("");
                return;
            }
            Registry r = LocateRegistry.getRegistry("127.0.0.1", 1234);
            ATM bank = (ATM) r.lookup("ATM");
            bank.retirar(this.cuenta, this.monto);
            String s = this.saldo+"";
            JOptionPane.showMessageDialog(null,"Se ha retirado de su cuenta N° "+this.cuenta+", se actualizo su saldo a "+s);
            
        }catch(Exception e){
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(null,"Disculpe, hubo un error en el sistema");
        }
        MenuB mb = new MenuB();
        mb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RetirarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retirar;
    private javax.swing.JComboBox<String> cbcuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
