package ClienteATM;

import RMI_ATM.ATM;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class Transferir extends javax.swing.JFrame {

    String doc_id;
    String[] cuentas;
    String cuenta;
    float saldo = 0;
    String monto;
    String cuentab;
    String docb;
    String desc;
 
    public Transferir(String doc) {
        this.doc_id = doc;
        initComponents();
        cuentas();
    }

    public void cuentas(){
        try{
            Registry r = LocateRegistry.getRegistry("127.0.0.1", 1234);
            ATM bank = (ATM) r.lookup("ATM");
            this.cuentas = bank.consultarcuentas(this.doc_id);
            int i = 0;
            while (i !=  6){
                if (this.cuentas[i]!=null){
                    String c = "N° de cuenta "+this.cuentas[i]+" con saldo de "+this.cuentas[i+1];
                    cbcuenta.addItem(c);
                }
                i = i + 2;
            }
        }catch(Exception e){
            System.out.print(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        Transferir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbcuenta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcuenta = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Transferir");

        volver.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        Transferir.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Transferir.setText("Transferir");
        Transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Cuenta a retirar");

        cbcuenta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Monto a transferir");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Cuenta del beneficiario");

        txtcuenta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuentaActionPerformed(evt);
            }
        });

        txtdescripcion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Descripción");

        txtdocumento.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Documento del beneficiario");

        txtmonto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(Transferir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcuenta)
                            .addComponent(txtdocumento)
                            .addComponent(txtdescripcion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmonto)
                            .addComponent(cbcuenta, 0, 296, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addComponent(Transferir)
                .addGap(18, 18, 18)
                .addComponent(volver)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        MenuT mt = new MenuT(this.doc_id);
        mt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverActionPerformed

    private void TransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferirActionPerformed
        try{
            boolean val = false;
            Registry r = LocateRegistry.getRegistry("127.0.0.1", 1234);
            ATM bank = (ATM) r.lookup("ATM");
            val = bank.verifdoccuenta(txtdocumento.getText(), txtcuenta.getText());
            if (val==false){
                JOptionPane.showMessageDialog(null, "El numero de cuenta del beneficiario no pertenece al documento ingresado");
                txtdocumento.setText("");
                txtcuenta.setText("");
                return;
            }
            this.monto = txtmonto.getText();
            Pattern p = Pattern.compile("[A-Z,a-z,&%$#@!()*^]"); 
            Matcher m = p.matcher(this.monto);
            if (m.find()|| Float.parseFloat(this.monto)<0){
                JOptionPane.showMessageDialog(null, "Por favor ingrese solo numeros positivos");
                txtmonto.setText("");
                return;
            }
            if (cbcuenta.getSelectedIndex()==0){
                this.cuenta = this.cuentas[0];
                this.saldo = Float.parseFloat(this.cuentas[1]) - Float.parseFloat(this.monto);
            }if (cbcuenta.getSelectedIndex()==1){
                this.cuenta = this.cuentas[2];
                this.saldo = Float.parseFloat(this.cuentas[3]) - Float.parseFloat(this.monto);
            }if(cbcuenta.getSelectedIndex()==2){
                this.cuenta = this.cuentas[4];
                this.saldo = Float.parseFloat(this.cuentas[5]) - Float.parseFloat(this.monto);
            }
            if (this.saldo<0){
                JOptionPane.showMessageDialog(null, "El monto colocado es superior al saldo de la cuenta");
                txtmonto.setText("");
                return;
            }
            this.docb = txtdocumento.getText();
            this.cuentab = txtcuenta.getText();
            this.desc = txtdescripcion.getText();
            if(this.desc.isEmpty()){
                JOptionPane.showMessageDialog(null, "Ingrese todos los datos para realizar la transferencia");
                return;
            }
            bank.transferir(this.cuenta, this.monto,this.cuentab,this.docb,this.desc);
            String s = this.saldo+"";
            JOptionPane.showMessageDialog(null,"Se ha realizado una transferencia de su cuenta N° "+this.cuenta+", se actualizo su saldo a "+s);
        }catch(Exception e){
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(null,"Disculpe, hubo un error en el sistema");
        }
        MenuB mb = new MenuB();
        mb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TransferirActionPerformed

    private void txtcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuentaActionPerformed

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void txtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Transferir;
    private javax.swing.JComboBox<String> cbcuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtcuenta;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
